//============================================================================
// Feature BRAM - Stores pre-computed spectral features for SVM classifier
// Target: Xilinx Artix-7 (Nexys 4 DDR)
//
// MEMORY LAYOUT:
//   Each test sample occupies 64 addresses (aligned for easy indexing):
//     [0:18]   = Stage 1 features (19 values)
//     [19:53]  = Stage 2 features (35 values)
//     [54:63]  = unused padding (for power-of-2 alignment)
//
//   Sample 0: addresses  0 -  63
//   Sample 1: addresses  64 - 127
//   Sample 2: addresses 128 - 191
//   ...
//   Sample 7: addresses 448 - 511
//
//   Total: 512 x 32-bit = 2 KB (fits in a single BRAM36)
//
// INITIALIZATION:
//   The BRAM is initialized from "feature_bram_init.hex" which is
//   generated by the MATLAB script "generate_bram_features.m"
//
// FORMAT: Q16.16 (32-bit signed, 16 fractional bits)
//
// BRAM INFERENCE NOTE:
//   When the write port (Port A) is tied off (we_a=0) in the parent
//   module, Vivado treats this as a ROM and ignores ram_style="block".
//   To force Block RAM inference we use BOTH:
//     - (* ram_style = "block" *)   for RAM inference path
//     - (* rom_style = "block" *)   for ROM inference path
//   Plus dont_touch prevents port optimization before BRAM mapping.
//
//   Ref: UG901 - Vivado Synthesis Guide, "RAM/ROM HDL Coding Techniques"
//============================================================================

`timescale 1ns / 1ps

(* dont_touch = "yes", keep_hierarchy = "yes" *)
module feature_bram #(
    parameter DATA_WIDTH = 32,
    parameter ADDR_WIDTH = 9,       // 2^9 = 512 locations
    parameter MEM_DEPTH  = 512,
    parameter INIT_FILE  = "feature_bram_init.hex"
)(
    // Port A: Write port (for future UART/SPI loading, currently unused)
    input  wire                    clk_a,
    input  wire                    we_a,
    input  wire [ADDR_WIDTH-1:0]   addr_a,
    input  wire [DATA_WIDTH-1:0]   din_a,
    output reg  [DATA_WIDTH-1:0]   dout_a,

    // Port B: Read-only port (used by bram_feature_loader)
    input  wire                    clk_b,
    input  wire [ADDR_WIDTH-1:0]   addr_b,
    output reg  [DATA_WIDTH-1:0]   dout_b
);

    // BRAM/ROM storage — dual attributes force Block RAM for BOTH paths
    (* ram_style = "block", rom_style = "block" *)
    reg [DATA_WIDTH-1:0] mem [0:MEM_DEPTH-1];

    // Initialize from hex file (supported for BRAM on Xilinx 7-series)
    initial begin
        $readmemh(INIT_FILE, mem);
    end

    // Port A: Read-first mode (Xilinx UG901 TDP BRAM inference template)
    always @(posedge clk_a) begin
        dout_a <= mem[addr_a];
        if (we_a)
            mem[addr_a] <= din_a;
    end

    // Port B: Read-only (simple synchronous read)
    always @(posedge clk_b) begin
        dout_b <= mem[addr_b];
    end

endmodule

